# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


Category.destroy_all
Subcategory.destroy_all


c1 = Category.create(:name => 'community')
c2 = Category.create(:name => 'housing')
c3 = Category.create(:name => 'personals')
c4 = Category.create(:name => 'for sale')
c5 = Category.create(:name => 'services')
c6 = Category.create(:name => 'jobs')

s1 = Subcategory.create(:name => 'activities', :category_id => c1.id)
s2 = Subcategory.create(:name => 'classes', :category_id => c1.id)
s3 = Subcategory.create(:name => 'events', :category_id => c1.id)
s4 = Subcategory.create(:name => 'car pools', :category_id => c1.id)
s5 = Subcategory.create(:name => 'general', :category_id => c1.id)
s6 = Subcategory.create(:name => 'lost + found', :category_id => c1.id)
s7 = Subcategory.create(:name => 'musicians', :category_id => c1.id)
s8 = Subcategory.create(:name => 'pets', :category_id => c1.id)
s9 = Subcategory.create(:name => 'politics', :category_id => c1.id)
s10 = Subcategory.create(:name => 'volunteers', :category_id => c1.id)


s11 = Subcategory.create(:name => 'flat/housing', :category_id => c2.id)
s12 = Subcategory.create(:name => 'holiday rentals', :category_id => c2.id)
s13 = Subcategory.create(:name => 'housing', :category_id => c2.id)
s14 = Subcategory.create(:name => 'housing swap', :category_id => c2.id)
s15 = Subcategory.create(:name => 'housing wanted', :category_id => c2.id)
s16 = Subcategory.create(:name => 'office / commercial', :category_id => c2.id)
s17 = Subcategory.create(:name => 'parking / storage', :category_id => c2.id)
s18 = Subcategory.create(:name => 'rooms/shared', :category_id => c2.id)
s19 = Subcategory.create(:name => 'rooms/wanted', :category_id => c2.id)
s20 = Subcategory.create(:name => 'sub-lets / temporary', :category_id => c2.id)

s21 = Subcategory.create(:name => 'strictly platonic', :category_id => c3.id)
s22 = Subcategory.create(:name => 'women seek women', :category_id => c3.id)
s23 = Subcategory.create(:name => 'women seeking men', :category_id => c3.id)
s24 = Subcategory.create(:name => 'men seeking women', :category_id => c3.id)
s25 = Subcategory.create(:name => 'misc romance', :category_id => c3.id)
s26 = Subcategory.create(:name => 'casual encounters', :category_id => c3.id)
s27 = Subcategory.create(:name => 'missed connections', :category_id => c3.id)
s28 = Subcategory.create(:name => 'rants and raves', :category_id => c3.id)

s29 = Subcategory.create(:name => 'antiques', :category_id => c4.id)
s30 = Subcategory.create(:name => 'appliances', :category_id => c4.id)
s31 = Subcategory.create(:name => 'arts + crafts', :category_id => c4.id)
s32 = Subcategory.create(:name => 'car pools', :category_id => c4.id)
s33 = Subcategory.create(:name => 'geatv/utv/sno', :category_id => c4.id)
s34 = Subcategory.create(:name => 'auto parts', :category_id => c4.id)
s35 = Subcategory.create(:name => 'baby + kid', :category_id => c4.id)
s36 = Subcategory.create(:name => 'banter', :category_id => c4.id)
s37 = Subcategory.create(:name => 'beauty+hlth', :category_id => c4.id)
s38 = Subcategory.create(:name => 'bikes', :category_id => c4.id)
s39 = Subcategory.create(:name => 'boats', :category_id => c4.id)
s40 = Subcategory.create(:name => 'books', :category_id => c4.id)
s41 = Subcategory.create(:name => 'business', :category_id => c4.id)
s42 = Subcategory.create(:name => 'caravn+mtrhm', :category_id => c4.id)
s43 = Subcategory.create(:name => 'cars+vans', :category_id => c4.id)
s44 = Subcategory.create(:name => 'cds/dvd/vhs', :category_id => c4.id)
s45 = Subcategory.create(:name => 'clothes+acc', :category_id => c4.id)
s46 = Subcategory.create(:name => 'collectables', :category_id => c4.id)
s47 = Subcategory.create(:name => 'computers', :category_id => c4.id)
s48 = Subcategory.create(:name => 'electronics', :category_id => c4.id)
s49 = Subcategory.create(:name => 'farm+garden', :category_id => c4.id)
s50 = Subcategory.create(:name => 'free', :category_id => c4.id)
s51 = Subcategory.create(:name => 'furniture', :category_id => c4.id)
s52 = Subcategory.create(:name => 'garage sale', :category_id => c4.id)
s53 = Subcategory.create(:name => 'general', :category_id => c4.id)
s54 = Subcategory.create(:name => 'heavy equipment', :category_id => c4.id)
s55 = Subcategory.create(:name => 'household', :category_id => c4.id)
s56 = Subcategory.create(:name => 'jewellery', :category_id => c4.id)
s57 = Subcategory.create(:name => 'materials', :category_id => c4.id)
s58 = Subcategory.create(:name => 'mobile phones', :category_id => c4.id)
s59 = Subcategory.create(:name => 'motorcycles', :category_id => c4.id)
s60 = Subcategory.create(:name => 'music instr', :category_id => c4.id)
s61 = Subcategory.create(:name => 'photo+video', :category_id => c4.id)
s62 = Subcategory.create(:name => 'sporting', :category_id => c4.id)
s63 = Subcategory.create(:name => 'tickets', :category_id => c4.id)
s64 = Subcategory.create(:name => 'tools', :category_id => c4.id)
s65 = Subcategory.create(:name => 'toys+games', :category_id => c4.id)
s66 = Subcategory.create(:name => 'video gaming', :category_id => c4.id)
s67 = Subcategory.create(:name => 'wanted', :category_id => c4.id)

s68 = Subcategory.create(:name => 'beauty', :category_id => c5.id)
s69 = Subcategory.create(:name => 'cars/automotive', :category_id => c5.id)
s70 = Subcategory.create(:name => 'computer', :category_id => c5.id)
s71 = Subcategory.create(:name => 'creative', :category_id => c5.id)
s72 = Subcategory.create(:name => 'cycle', :category_id => c5.id)
s73 = Subcategory.create(:name => 'event', :category_id => c5.id)
s74 = Subcategory.create(:name => 'farm+garden', :category_id => c5.id)
s75 = Subcategory.create(:name => 'financial', :category_id => c5.id)
s76 = Subcategory.create(:name => 'household', :category_id => c5.id)
s77 = Subcategory.create(:name => 'housing/real estate', :category_id => c5.id)
s78 = Subcategory.create(:name => 'labour/move', :category_id => c5.id)
s79 = Subcategory.create(:name => 'legal', :category_id => c5.id)
s80 = Subcategory.create(:name => 'lesson', :category_id => c5.id)
s81 = Subcategory.create(:name => 'marine', :category_id => c5.id)
s82 = Subcategory.create(:name => 'pet', :category_id => c5.id)
s83 = Subcategory.create(:name => 'skilled trade', :category_id => c5.id)
s84 = Subcategory.create(:name => 'sm biz ads', :category_id => c5.id)
s85 = Subcategory.create(:name => 'therapeutic', :category_id => c5.id)
s86 = Subcategory.create(:name => 'travel/hol', :category_id => c5.id)
s87 = Subcategory.create(:name => 'write/ed/tr8', :category_id => c5.id)

s88 = Subcategory.create(:name => 'antiques', :category_id => c6.id)
s89 = Subcategory.create(:name => 'appliances', :category_id => c6.id)
s90 = Subcategory.create(:name => 'arts + crafts', :category_id => c6.id)
s91 = Subcategory.create(:name => 'car pools', :category_id => c6.id)
s92 = Subcategory.create(:name => 'geatv/utv/sno', :category_id => c6.id)
s93 = Subcategory.create(:name => 'auto parts', :category_id => c6.id)
s94 = Subcategory.create(:name => 'baby + kid', :category_id => c6.id)
s95 = Subcategory.create(:name => 'banter', :category_id => c6.id)
s96 = Subcategory.create(:name => 'beauty+hlth', :category_id => c6.id)
s97 = Subcategory.create(:name => 'bikes', :category_id => c6.id)
s98 = Subcategory.create(:name => 'boats', :category_id => c6.id)
s99 = Subcategory.create(:name => 'books', :category_id => c6.id)
s100 = Subcategory.create(:name => 'business', :category_id => c6.id)
s101 = Subcategory.create(:name => 'caravn+mtrhm', :category_id => c6.id)
s102 = Subcategory.create(:name => 'cars+vans', :category_id => c6.id)
s103 = Subcategory.create(:name => 'cds/dvd/vhs', :category_id => c6.id)
s104 = Subcategory.create(:name => 'clothes+acc', :category_id => c6.id)
s105 = Subcategory.create(:name => 'collectables', :category_id => c6.id)
s106 = Subcategory.create(:name => 'computers', :category_id => c6.id)
s107 = Subcategory.create(:name => 'electronics', :category_id => c6.id)
s108 = Subcategory.create(:name => 'farm+garden', :category_id => c6.id)
s109 = Subcategory.create(:name => 'free', :category_id => c6.id)
s110 = Subcategory.create(:name => 'furniture', :category_id => c6.id)
s111 = Subcategory.create(:name => 'garage sale', :category_id => c6.id)
s112 = Subcategory.create(:name => 'general', :category_id => c6.id)
s113 = Subcategory.create(:name => 'heavy equipment', :category_id => c6.id)
s114 = Subcategory.create(:name => 'household', :category_id => c6.id)
s115 = Subcategory.create(:name => 'jewellery', :category_id => c6.id)
s116 = Subcategory.create(:name => 'materials', :category_id => c6.id)
s117 = Subcategory.create(:name => 'mobile phones', :category_id => c6.id)
s118 = Subcategory.create(:name => 'motorcycles', :category_id => c6.id)
s119 = Subcategory.create(:name => 'music instr', :category_id => c6.id)
s120 = Subcategory.create(:name => 'photo+video', :category_id => c6.id)
s121 = Subcategory.create(:name => 'sporting', :category_id => c6.id)
s122 = Subcategory.create(:name => 'tickets', :category_id => c6.id)
s123 = Subcategory.create(:name => 'tools', :category_id => c6.id)
s124 = Subcategory.create(:name => 'toys+games', :category_id => c6.id)
s125 = Subcategory.create(:name => 'video gaming', :category_id => c6.id)
s126 = Subcategory.create(:name => 'wanted', :category_id => c6.id)



# c1 = Category.create(name: => 'community').first_or_create(name: 'community')
# housing_category - Category.create(name: 'housing').first_or_create(name: 'housing')

# Subcategory.where(name: 'activities', category_id: community_category.id).first_or_create(name: 'activities', community_category.id)
# Subcategory.where(name: 'classes', category_id:  community_category.id).first_or_create(name: 'classes', community_category.id)
# Subcategory.where(name: 'events', category_id: community_category.id).first_or_create(name: 'events', community_category.id)